### ISSUE TITLE
Unable to extract 7z archives with long paths

### ISSUE THREAD

**Issue by asrabon** [miurahr/py7zr#116] opened 2020-04-18 05:34 UTC
If you create any 7z archive that has a path over 255 characters(8.3 naming convention). The program will fail to unpack them and give a "_lzma.LZMAError". If the archive contains some files that aren't in a ton of subdirectories to the point where the file falls into the 8.3 naming convention it will extract those fine it is just when it comes across a file with a 7zip file path of more than 255 characters.

**Comment by miurahr** [comment] 2020-04-18 15:48
Could @asrabon upload a simple data which include a path over 255 characters which cause the issue?

**Comment by asrabon** [comment] 2020-04-18 16:20
Here is the file if you need any additional samples please just let me know I will be glad to provide some. The file is a zip of the 7z file since github doesn't allow uploads of 7zs.

[7zip with short path and long path.zip](https://github.com/miurahr/py7zr/files/4496991/7zip.with.short.path.and.long.path.zip)

**Comment by miurahr** [comment] 2020-04-18 16:42
When running `7z x longpath.7z` with p7zip on linux, it produce error as follows:

```
$ env LANG=C 7z x ~/projects/py7zr/tests/data/longpath.7z 

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=C,Utf16=off,HugeFiles=on,64 bits,4 CPUs Intel(R) Core(TM) i3-6100U CPU @ 2.30GHz (406E3),ASM,AES-NI)

Scanning the drive for archives:
1 file, 1079 bytes (2 KiB)                        

Extracting archive: /home/miurahr/projects/py7zr/tests/data/longpath.7z
--
Path = /home/miurahr/projects/py7zr/tests/data/longpath.7z
Type = 7z
Physical Size = 1079
Headers Size = 413
Method = LZMA2:12
Solid = -
Blocks = 2

ERROR: Can not open output file : File name too long : ./Users\AnthonyRabon\Downloads\CJ_WS_Spectre-v040920R1_2020-04-09_23-40-44 (1)\CJ_WS_Spectre-v040920R1_2020-04-09_23-40-44\Suspicious Files\Program Files\WindowsApps\AD2F1837.HPPrinterControl_110.1.671.0_x64__v10z8vjag6ke6\HP.Framework.Extensions.ScanCapture\Assets\Arrow.png\Arrow.png\Arrow.png
                                                                        
Sub items Errors: 1

Archives with Errors: 1

Sub items Errors: 1
```

Does it really extract correctly on your platform?

With py7zr, it also become OS error.

```
$ env LANG=C py7zr x ~/projects/py7zr/tests/data/longpath.7z 
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/miurahr/.virtualenvs/py7zr38/lib/python3.8/site-packages/py7zr/compression.py", line 223, in extract_single
    with fileish.open(mode='wb') as ofp:
  File "/usr/lib/python3.8/pathlib.py", line 1213, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib/python3.8/pathlib.py", line 1069, in _opener
    return self._accessor.open(self, flags, mode)
OSError: [Errno 36] File name too long: 'Users\\AnthonyRabon\\Downloads\\CJ_WS_Spectre-v040920R1_2020-04-09_23-40-44 (1)\\CJ_WS_Spectre-v040920R1_2020-04-09_23-40-44\\Suspicious Files\\Program Files\\WindowsApps\\AD2F1837.HPPrinterControl_110.1.671.0_x64__v10z8vjag6ke6\\HP.Framework.Extensions.ScanCapture\\Assets\\Arrow.png\\Arrow.png\\Arrow.png'
Traceback (most recent call last):
  File "/home/miurahr/.virtualenvs/py7zr38/bin/py7zr", line 10, in <module>
    sys.exit(main())
  File "/home/miurahr/.virtualenvs/py7zr38/lib/python3.8/site-packages/py7zr/__init__.py", line 43, in main
    return cli.run()
  File "/home/miurahr/.virtualenvs/py7zr38/lib/python3.8/site-packages/py7zr/cli.py", line 39, in run
    return args.func(args)
  File "/home/miurahr/.virtualenvs/py7zr38/lib/python3.8/site-packages/py7zr/cli.py", line 209, in run_extract
    a.extractall()
  File "/home/miurahr/.virtualenvs/py7zr38/lib/python3.8/site-packages/py7zr/py7zr.py", line 710, in extractall
    return self.extract(path)
  File "/home/miurahr/.virtualenvs/py7zr38/lib/python3.8/site-packages/py7zr/py7zr.py", line 805, in extract
    self._set_file_property(o, p)
  File "/home/miurahr/.virtualenvs/py7zr38/lib/python3.8/site-packages/py7zr/py7zr.py", line 475, in _set_file_property
    os.utime(str(outfilename), times=(creationtime, creationtime))
OSError: [Errno 36] File name too long
```

Py7zr should catch os error and show better error message at least.

**Comment by miurahr** [comment] 2020-04-18 16:48
I'm wondering that the test data has a 'backslash` for path separator and p7zip and py7zr understand it is a part of filename not path separator. Then p7zip and py7zr try to create a filename which has a backslash as a part of filename with length is over > 255. It may cause an OS error because many file system has a limitation of filename length as 255 bytes.

On linux, it allow 4096 bytes for path length.

**Comment by asrabon** [comment] 2020-04-18 16:53
I have been using 7zip on windows and it has been extracting the files without issues. 

Whenever I iterate through through the list of files in the archive and attempt to extract each one individually. When it hits one with a long path it will eventually give the LZMAError I mentioned above when it attempts to decompress the data.

**Comment by miurahr** [comment] 2020-04-18 17:12
I cannot reproduce LZMA error.
Could you post an execution messages?

**Comment by miurahr** [comment] 2020-05-08 15:32
@asrabon I just found Windows has a limitation MAX_PATH in 260 bytes.
How did you handle it?
 
see https://bugs.python.org/issue27731

**Comment by miurahr** [comment] 2020-05-08 15:40
I've added a test case with the file you upload and get an error. Is it a similar error you observed?

Test case:
```
def test_extract_longpath_file(tmp_path):
    with py7zr.SevenZipFile(testdata_path.joinpath('longpath.7z').open('rb')) as archive:
        archive.extractall(path=tmp_path)
```

log on AppVeyor  https://ci.appveyor.com/project/miurahr/py7zr/builds/32742385
```
[00:02:53] 
[00:02:53] ================================== FAILURES ===================================
[00:02:53] _________________________ test_extract_longpath_file __________________________
[00:02:53] 
[00:02:53] tmp_path = WindowsPath('C:/Users/appveyor/AppData/Local/Temp/1/pytest-of-unknown/pytest-0/test_extract_longpath_file0')
[00:02:53] 
[00:02:53]     @pytest.mark.files
[00:02:53]     def test_extract_longpath_file(tmp_path):
[00:02:53]         with py7zr.SevenZipFile(testdata_path.joinpath('longpath.7z').open('rb')) as archive:
[00:02:53] >           archive.extractall(path=tmp_path)
[00:02:53] 
[00:02:53] C:\projects\py7zr\tests\test_extract.py:423: 
[00:02:53] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
[00:02:53] C:\projects\py7zr\py7zr\py7zr.py:674: in extractall
[00:02:53]     self._extract(path=path, return_dict=False)
[00:02:53] C:\projects\py7zr\py7zr\py7zr.py:761: in _extract
[00:02:53]     self.worker.extract(self.fp, parallel=(not self.password_protected and not self._filePassed))
[00:02:53] C:\projects\py7zr\py7zr\compression.py:81: in extract
[00:02:53]     self.src_start + positions[i + 1])
[00:02:53] C:\projects\py7zr\py7zr\compression.py:109: in extract_single
[00:02:53]     os.makedirs(fileish.parent)
[00:02:53] C:\projects\py7zr\.tox\py37\lib\os.py:211: in makedirs
[00:02:53]     makedirs(head, exist_ok=exist_ok)
[00:02:53] C:\projects\py7zr\.tox\py37\lib\os.py:211: in makedirs
[00:02:53]     makedirs(head, exist_ok=exist_ok)
[00:02:53] C:\projects\py7zr\.tox\py37\lib\os.py:211: in makedirs
[00:02:53]     makedirs(head, exist_ok=exist_ok)
[00:02:53] C:\projects\py7zr\.tox\py37\lib\os.py:211: in makedirs
[00:02:53]     makedirs(head, exist_ok=exist_ok)
[00:02:53] C:\projects\py7zr\.tox\py37\lib\os.py:211: in makedirs
[00:02:53]     makedirs(head, exist_ok=exist_ok)
[00:02:53] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
[00:02:53] 
[00:02:53] name = 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pytest-of-unknown\\pytest-0\\test_extract_longpath_file0\\Users\\Anthon...0R1_2020-04-09_23-40-44 (1)\\CJ_WS_Spectre-v040920R1_2020-04-09_23-40-44\\Suspicious Files\\Program Files\\WindowsApps'
[00:02:53] mode = 511, exist_ok = False
[00:02:53] 
[00:02:53]     def makedirs(name, mode=0o777, exist_ok=False):
[00:02:53]         """makedirs(name [, mode=0o777][, exist_ok=False])
[00:02:53]     
[00:02:53]         Super-mkdir; create a leaf directory and all intermediate ones.  Works like
[00:02:53]         mkdir, except that any intermediate path segment (not just the rightmost)
[00:02:53]         will be created if it does not exist. If the target directory already
[00:02:53]         exists, raise an OSError if exist_ok is False. Otherwise no exception is
[00:02:53]         raised.  This is recursive.
[00:02:53]     
[00:02:53]         """
[00:02:53]         head, tail = path.split(name)
[00:02:53]         if not tail:
[00:02:53]             head, tail = path.split(head)
[00:02:53]         if head and tail and not path.exists(head):
[00:02:53]             try:
[00:02:53]                 makedirs(head, exist_ok=exist_ok)
[00:02:53]             except FileExistsError:
[00:02:53]                 # Defeats race condition when another thread created the path
[00:02:53]                 pass
[00:02:53]             cdir = curdir
[00:02:53]             if isinstance(tail, bytes):
[00:02:53]                 cdir = bytes(curdir, 'ASCII')
[00:02:53]             if tail == cdir:           # xxx/newdir/. exists if xxx/newdir exists
[00:02:53]                 return
[00:02:53]         try:
[00:02:53] >           mkdir(name, mode)
[00:02:53] E           FileNotFoundError: [WinError 206] The filename or extension is too long: 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pytest-of-unknown\\pytest-0\\test_extract_longpath_file0\\Users\\AnthonyRabon\\Downloads\\CJ_WS_Spectre-v040920R1_2020-04-09_23-40-44 (1)\\CJ_WS_Spectre-v040920R1_2020-04-09_23-40-44\\Suspicious Files\\Program Files\\WindowsApps'
[00:02:53] 
[00:02:53] C:\projects\py7zr\.tox\py37\lib\os.py:221: FileNotFoundError
```

**Comment by miurahr** [comment] 2020-05-09 03:00
Update, I've added modification of registory entry and update py7zr code then it seems solved.

```
New-ItemProperty -Path Registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem -Name 'LongPathsEnabled' -Type DWord -Value 1
LongPathsEnabled : 1
PSPath           : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem
PSParentPath     : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control
PSChildName      : FileSystem
PSProvider       : Microsoft.PowerShell.Core\Registry
```
https://ci.appveyor.com/project/miurahr/py7zr/build/job/m6m4xnjvur2d4r78

**Comment by miurahr** [comment] 2020-05-09 04:36
v0.7.0b2 released with enhancement for this.
Could you test the release whether improve your situation with it?

**Comment by miurahr** [comment] 2020-05-13 06:27
Do not get a negative feedback. Close now but please reopen when not fixes  your case.

**Closed by miurahr** 2020-05-13 06:27 UTC
Labels: bug, for extraction, windows
