### ISSUE TITLE
Ability to interact with 7zip file with file name encryption

### ISSUE THREAD

**Issue by maki43** [miurahr/py7zr#139] opened 2020-06-02 23:09 UTC
**Is your feature request related to a problem? Please describe.**
When attempting to read a 7zip that has file name encryption turned on an unsupported encryption message is returned and it can't be read.

**Describe the solution you'd like**
Ability to read the file the same way as with an encrypted 7zip file that has been created without the file name encryption option

**Describe alternatives you've considered**
7zip command line extraction is only alternative right now.

**Additional context**
N/A

**Comment by miurahr** [comment] 2020-06-03 00:35
Could you upload test data and describe its filenames, password, encryption method, and encryption parameters?
Could you also share a documentation or URL link of the specification of filename encryption?

**Comment by maki43** [comment] 2020-06-03 00:55
Here is a sample file with password 'hello':
[Link](https://cp.sync.com/dl/927adc250/n4jjttcb-yd7vf4r3-ps46hyrg-4g2gfshr)

Using this script:
` zip = SevenZipFile(file = z['fullfilepath'],mode='r',password='hello')`

These are the settings with the only difference being the file name encryption.

![image](https://user-images.githubusercontent.com/66338680/83583665-dd70cf00-a53c-11ea-951d-2b171ab220b3.png)

**Comment by miurahr** [comment] 2020-06-03 01:15
Do you know what is a filename encryption as in technical specification?  Because I don't know it, so I would like to ask help for one who knows its specification to send Pull-Request.

**Comment by maki43** [comment] 2020-06-03 01:33
I'm afraid i do not know, this is just a standard settings in 7zip which I have used.  If i do find anything though i will make sure to post the information.

I have several multiple gigabyte zips that are encrypted like this with thousands of files/folders inside which i need to analyse.

**Comment by miurahr** [comment] 2020-06-03 01:39
Thanks for information. I've just added test case marked as an 'expected failure' because of not implemented yet.

When run test case I've got
```
tests/test_info.py:160 (test_list_filename_encryption)
tmp_path = PosixPath('/tmp/pytest-of-miurahr/pytest-55/test_list_filename_encryption0')

    @pytest.mark.files
    @pytest.mark.xfails(reason="Not implemented yet")
    def test_list_filename_encryption(tmp_path):
>       with py7zr.SevenZipFile(os.path.join(testdata_path, 'filename_encryption.7z'), 'r', password='hello') as ar:

tests/test_info.py:164: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
py7zr/py7zr.py:346: in __init__
    raise e
py7zr/py7zr.py:330: in __init__
    self._real_get_contents(self.fp)
py7zr/py7zr.py:382: in _real_get_contents
    header = Header.retrieve(self.fp, buffer, self.afterheader)
py7zr/archiveinfo.py:877: in retrieve
    obj._read(fp, buffer, start_pos)
py7zr/archiveinfo.py:883: in _read
    self._decode_header(fp, buffer)
py7zr/archiveinfo.py:902: in _decode_header
    self._decode_header(fp, self._get_headerdata_from_streams(fp, streams))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <py7zr.archiveinfo.Header object at 0x7fa738b8d400>
fp = <_io.BufferedReader name='/home/miurahr/projects/py7zr/tests/data/filename_encryption.7z'>
streams = <py7zr.archiveinfo.HeaderStreamsInfo object at 0x7fa738a80090>

    def _get_headerdata_from_streams(self, fp: BinaryIO, streams: StreamsInfo) -> BytesIO:
        """get header data from given streams.unpackinfo and packinfo.
        folder data are stored in raw data positioned in afterheader."""
        buffer = io.BytesIO()
        src_start = self._start_pos
        for folder in streams.unpackinfo.folders:
            if folder.is_encrypted():
>               raise UnsupportedCompressionMethodError()
E               py7zr.exceptions.UnsupportedCompressionMethodError

py7zr/archiveinfo.py:911: UnsupportedCompressionMethodError
```

This seems be a good start point for me.

**Comment by miurahr** [comment] 2020-06-04 05:25
Implemented #140, merged and released as v0.7.3 
Could @maki43 give a feedback for v0.7.3?

**Comment by miurahr** [comment] 2020-06-07 05:12
Regression test is also added with the file provided by @maki43, so I'd like to close here.

**Closed by miurahr** 2020-06-07 05:12 UTC
Labels: enhancement, feedback, for extraction

**Comment by maki43** [comment] 2020-06-13 07:27
@miurahr  Sorry I have only just got around to test it. Worked perfectly on a 3gb file. Thank you for adding this feature!
