### ISSUE TITLE
writestr support just like ZipFile.writestr

### ISSUE THREAD

**Issue by BioEvo** [miurahr/py7zr#290] opened 2021-02-04 11:30 UTC
**Is your feature request related to a problem? Please describe.**
It seems like there is no writestr method in py7zr

**Describe the solution you'd like**
in ZipFile, there i got ZipFile.writestr(zinfo_or_arcname, data, compress_type=None, compresslevel=None)

**Describe alternatives you've considered**
SevenZipFile.writestr(data, arcname)

**Comment by miurahr** [comment] 2021-02-06 06:29
@BioEvo  Does #293 works for you?

**Comment by miurahr** [comment] 2021-02-06 07:10
In #293 implementation, I wraps  `data: bytes` with `io.BytesIO(data)`.
Because `readall()` and `read()` methods returns BytesIO() object, accepting BInaryIO object is an alternative candidate.

**Comment by BioEvo** [comment] 2021-02-06 13:33
> @BioEvo Does #293 works for you?

I works,  thank you!

**Comment by miurahr** [comment] 2021-02-12 08:46
PR merged.

**Comment by hildogjr** [comment] 2021-02-18 14:01
`tarfile` and `zipfile` libraries on Python use `writestr(arc_name, data, foo)` and here was merged `writestr(data, arc_name)`. Should we keep the same order for better code compatibility? (and before official release on PyPI).

I put a propose on https://github.com/miurahr/py7zr/pull/300.

**Comment by miurahr** [comment] 2021-02-18 14:43
SevenZipFile has methods
` def write(self, file: Union[pathlib.Path, str], arcname: Optional[str] = None):`
and 
`def writeall(self, path: Union[pathlib.Path, str], arcname: Optional[str] = None):`

which has a consistency with current argument order.
#300 breaks consistency in SevenZipFile class.

**Comment by miurahr** [comment] 2021-02-19 00:12
v.0.13.0 is out.

**Closed by miurahr** 2021-02-19 00:12 UTC
Labels: enhancement, for archiving

**Comment by hildogjr** [comment] 2021-02-19 01:06
Thanks @miurahr. I also started some tests on my in-development application. The bellow code is a comparison between generate a .zip and a .7z file from Python (just to reproduce my "maybe-issue").

Generated ZIP: [test.zip](https://github.com/miurahr/py7zr/files/6006899/test.zip)

Generated 7z (remove the ".txt" at the end): [test.7z.txt](https://github.com/miurahr/py7zr/files/6006900/test.7z.txt)

The 7z file is marked as invalid by my OS. Did I forgot some parameter/configuration?


```python
import py7zr, zipfile
from io import BytesIO
fh=open('image.jpg', 'rb') # Use the inside ZIP file to reproduce.
data=fh.read()
fh.close()

data_z=BytesIO()
fz=zipfile.ZipFile(data_z, mode='w', compression=zipfile.ZIP_DEFLATED)
fz.writestr('image.jpg',data)
fz.close()
fh=open('test.zip', 'wb')
fh.write(data_z.getvalue())
fh.close()

data_7=BytesIO()
f7=py7zr.SevenZipFile(data_7, mode='w')
f7.writestr(data,'image.jpg')
f7.close()
fh=open('test.7z','wb')
fh.write(data_7.getvalue())
fh.close()
```

**Comment by miurahr** [comment] 2021-02-19 01:58
p7zip test command said the attachment is valid 7z file.

could you post details of actual error?

```
$ 7z t test.7z 

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=ja_JP.UTF-8,Utf16=on,HugeFiles=on,64 bits,16 CPUs AMD Ryzen 7 PRO 4750U with Radeon Graphics (860F01),ASM,AES-NI)

Scanning the drive for archives:
1 file, 31740 bytes (31 KiB)

Testing archive: test.7z
--
Path = test.7z
Type = 7z
Physical Size = 31740
Headers Size = 159
Method = LZMA2:24 BCJ
Solid = -
Blocks = 1

Everything is Ok

Size:       32517
Compressed: 31740
```

**Comment by hildogjr** [comment] 2021-02-19 02:05
I just write the file and try to open:
![image](https://user-images.githubusercontent.com/2211474/108446613-2c7ea180-723d-11eb-9273-5cca6d134922.png)

A comparison with the of file generate:
```bash
ls -l
-rw-rw-r-- 1 lab lab     31721 fev 18 21:52 test_by_OS.7z
-rw-rw-r-- 1 lab lab     31740 fev 18 21:59 test.7z
-rw-rw-r-- 1 lab lab     31607 fev 18 21:58 test.zip

```

The file generated by the OS is slight bigger 31721 vs 31607 bytes. So, I was suspecting that I forgot to active some header on the generation.

**Comment by miurahr** [comment] 2021-02-19 02:12
Could you post details of running environment?
Also could you collect log file or similar information?

It can be different size when using another tool, and it is NOT a problem.

**Comment by hildogjr** [comment] 2021-02-19 02:23
My system: Linux lab-Inspiron-7560 5.8.0-43-generic #49~20.04.1-Ubuntu SMP Fri Feb 5 09:57:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Application that I used to open the files: Archive Manager 3.36.3 (An archive manager for GNOME)

I will try to open in open OS to check again.

**Comment by miurahr** [comment] 2021-02-19 02:37
Could you test your archive with `7z`  or `7za` command with `7z t test.7z`?

My archive manager 3.36.3 on Mint Linux 20 works well.

archive manager is actually `file-roller` package and It suggest installing `p7zip-full` package
for supporting 7z file. do you have p7zip-full package? 

```
$ apt shw file-roller
Package: file-roller
Version: 3.36.3-0ubuntu1
Priority: optional
Section: gnome

Suggests: p7zip-full, arj, lha, lzip, lzma, lzop, ncompress, rpm2cpio, rzip, sharutils, squashfs-tools, unace, unalz, unar, xz-utils, zoo

Description: archive manager for GNOME

```

**Comment by hildogjr** [comment] 2021-02-19 02:50
It worked fine in Windows WinRAR. So some imitation of Gnome application.

**Comment by miurahr** [comment] 2021-02-19 03:41
Can you run `7z --help` on Linux?

**Comment by hildogjr** [comment] 2021-02-19 14:40
You are absolutely right, after `apt install p7zip-full` the file opened perfect fine even on the GUI of Archive Manager.

I remember that Ubuntu 16.04 had not the 7zip capability (and I always installed such package), strange is the 20.04 have the option to generate the `test_by_OS.7z` file and open correct by not open `test.7z`.

You Python library is perfect, I just have to dig and understanding this OS behavior (not related with you library).
